config/routes.rb
Jtbookstore::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :images


  resources :actors


  resources :books do
    member do
      get :sendmail
    end
    collection do
      get :search
      post :search
    end
  end

  resources :stores


  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users

  resources :users

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  belongs_to :user
  has_many :stores, :dependent => :destroy

  attr_accessible :achievement, :devote, :id, :levels, :name, :points, :sex
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @actors }
    end
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
    @actor = Actor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @actor }
    end
  end

  # GET /actors/new
  # GET /actors/new.json
  def new
    @actor = Actor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @actor }
    end
  end

  # GET /actors/1/edit
  def edit
    @actor = Actor.find(params[:id])
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(params[:actor])

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render json: @actor, status: :created, location: @actor }
      else
        format.html { render action: "new" }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /actors/1
  # PUT /actors/1.json
  def update
    @actor = Actor.find(params[:id])

    respond_to do |format|
      if @actor.update_attributes(params[:actor])
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor = Actor.find(params[:id])
    @actor.destroy

    respond_to do |format|
      format.html { redirect_to actors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/views/actors/_form.html.haml
= simple_form_for(@actor) do |f|
  = f.error_notification

  .form-inputs
    = f.input :id
    = f.input :name
    = f.input :sex
    = f.input :achievement
    = f.input :points
    = f.input :devote
    = f.input :levels

  .form-actions
    = f.button :submit

app/views/actors/edit.html.haml
%h1 Editing actor

= render 'form'

= link_to 'Show', @actor
\|
= link_to 'Back', actors_path

app/views/actors/index.html.haml
%h1 Listing actors

%table
  %tr
    %th Id
    %th Name
    %th Sex
    %th Achievement
    %th Points
    %th Devote
    %th Levels
    %th
    %th
    %th

  - @actors.each do |actor|
    %tr
      %td= actor.id
      %td= actor.name
      %td= actor.sex
      %td= actor.achievement
      %td= actor.points
      %td= actor.devote
      %td= actor.levels
      %td= link_to 'Show', actor
      %td= link_to 'Edit', edit_actor_path(actor)
      %td= link_to 'Destroy', actor, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Actor', new_actor_path

app/views/actors/new.html.haml
%h1 New actor

= render 'form'

= link_to 'Back', actors_path

app/views/actors/show.html.haml
%p#notice= notice

%p
  %b Id:
  = @actor.id
%p
  %b Name:
  = @actor.name
%p
  %b Sex:
  = @actor.sex
%p
  %b Achievement:
  = @actor.achievement
%p
  %b Points:
  = @actor.points
%p
  %b Devote:
  = @actor.devote
%p
  %b Levels:
  = @actor.levels

= link_to 'Edit', edit_actor_path(@actor)
\|
= link_to 'Back', actors_path