config/routes.rb
Jtbookstore::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :images


  resources :actors


  resources :books do
    member do
      get :sendmail
    end
    collection do
      get :search
      post :search
    end
  end

  resources :stores


  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users

  resources :users

end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :actor
  has_many :books, :dependent => :destroy

  attr_accessible :sdescript, :id, :sname, :stype
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stores }
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @store = Store.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/new
  # GET /stores/new.json
  def new
    @store = Store.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/1/edit
  def edit
    @store = Store.find(params[:id])
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(params[:store])

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render json: @store, status: :created, location: @store }
      else
        format.html { render action: "new" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stores/1
  # PUT /stores/1.json
  def update
    @store = Store.find(params[:id])

    respond_to do |format|
      if @store.update_attributes(params[:store])
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store = Store.find(params[:id])
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.haml
= simple_form_for(@store) do |f|
  = f.error_notification

  .form-inputs
    = f.input :sid
    = f.input :sname
    = f.input :stype
    = f.input :sdescript

  .form-actions
    = f.button :submit

app/views/stores/edit.html.haml
%h1 Editing store

= render 'form'

= link_to 'Show', @store
\|
= link_to 'Back', stores_path

app/views/stores/index.html.haml
%h1 Listing stores

%table
  %tr
    %th Sid
    %th Sname
    %th Stype
    %th Sdescript
    %th
    %th
    %th

  - @stores.each do |store|
    %tr
      %td= store.sid
      %td= store.sname
      %td= store.stype
      %td= store.sdescript
      %td= link_to 'Show', store
      %td= link_to 'Edit', edit_store_path(store)
      %td= link_to 'Destroy', store, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Store', new_store_path

app/views/stores/new.html.haml
%h1 New store

= render 'form'

= link_to 'Back', stores_path

app/views/stores/show.html.haml
%p#notice= notice

%p
  %b Sid:
  = @store.sid
%p
  %b Sname:
  = @store.sname
%p
  %b Stype:
  = @store.stype
%p
  %b Sdescript:
  = @store.sdescript

= link_to 'Edit', edit_store_path(@store)
\|
= link_to 'Back', stores_path