config/routes.rb
Jtbookstore::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :images


  resources :actors


  resources :books do
    member do
      get :sendmail
    end
    collection do
      get :search
      post :search
    end
  end

  resources :stores


  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users

  resources :users

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :store
  has_many :images, :dependent => :destroy
  accepts_nested_attributes_for :images, :allow_destroy => true

  attr_accessible :bdescript, :id, :bname, :bprice, :bpublication, :btype

  searchable do
    text :bname, :bdescript
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  def search
    res = Book.search do
      keywords params[:stext]
    end
    @searchresult = res.results

    respond_to do |format|
      format.html
      format.json { head :no_content }
      format.js {render :layout => false}
    end
  end

  require 'resque'
  require 'thrift'
  #$:.push("../thrift")
  require 'Authentication'
  require 'myauth_constants'


  def cox
    puts 'xxxxxxxxxxxxxxxxx'
  end

  def sendmail
    @uid = params[:id]

    # Do anything here, like access models, etc

    begin
      transport = Thrift::BufferedTransport.new(Thrift::HTTPClientTransport.new('http://127.0.0.1:4000/ccb'))
      protocol = Thrift::BinaryProtocol.new(transport)
      client = MyAuth::Authentication::Client.new(protocol)
      transport.open

      user = MyAuth::User.new
      user.username = 'james'
      user.password = 'fuckyou'

      puts "Login: #{client.login(user)}"
    rescue => e
      logger.error "shirft error: #{e.message}"
      puts "shirft error: #{e.message}"
    end

    Resque.enqueue MailWorker

    redirect_to :root
  end

end

app/helpers/books_helper.rb
module BooksHelper
  def cox
    puts 'ksjdflsajflsajfklsjflskf'
  end
end

app/views/books/_form.html.haml
= simple_form_for(@book) do |f|
  = f.error_notification

  .form-inputs
    = f.input :bname
    = f.input :btype
    = f.input :bdescript
    = f.input :bprice
    = f.input :bpublication

  .form-actions
    = f.button :submit

app/views/books/_search.html.haml
%thead
  %tr.info
    %th index
    %th bookname
    %th bookdescription
    %th bookprice
%tbody
  - @searchresult.each do |result|
    %tr
      %th= 1
      %th= result.bname
      %th= result.bdescript
      %th= result.bprice

app/views/books/edit.html.haml
%h1 Editing book

= render 'form'

= link_to 'Show', @book
\|
= link_to 'Back', books_path

app/views/books/index.html.erb
<div class="container">
  <h2>Upload file</h2>
  <%= form_for Image.new, :html => { :multipart => true, :id => "fileupload"  } do |f| %>
      <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
      <div class="row fileupload-buttonbar">
        <div class="span7">
          <!-- The fileinput-button span is used to style the file input field as button -->
        <span class="btn btn-success fileinput-button">
          <i class="icon-plus icon-white"></i>
          <span>Add files...</span>
          <%= f.file_field :image %>
        </span>
          <button type="submit" class="btn btn-primary start">
            <i class="icon-upload icon-white"></i>
            <span>Start upload</span>
          </button>
          <button type="reset" class="btn btn-warning cancel">
            <i class="icon-ban-circle icon-white"></i>
            <span>Cancel upload</span>
          </button>
          <button type="button" class="btn btn-danger delete">
            <i class="icon-trash icon-white"></i>
            <span>Delete</span>
          </button>
          <input type="checkbox" class="toggle">
        </div>
        <div class="span5">
          <!-- The global progress bar -->
          <div class="progress progress-success progress-striped active fade">
            <div class="bar" style="width:0%;"></div>
          </div>
        </div>
      </div>
      <!-- The loading indicator is shown during image processing -->
      <div class="fileupload-loading"></div>
      <br>
      <!-- The table listing the files available for upload/download -->
      <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
      </table>
  <% end %>

</div>
<script>
    var fileUploadErrors = {
        maxFileSize: 'File is too big',
        minFileSize: 'File is too small',
        acceptFileTypes: 'Filetype not allowed',
        maxNumberOfFiles: 'Max number of files exceeded',
        uploadedBytes: 'Uploaded bytes exceed file size',
        emptyResult: 'Empty file upload result'
    };
</script>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  <tr class="template-upload fade">
    <td class="preview"><span class="fade"></span></td>
    <td class="name"><span>{%=file.name%}</span></td>
    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
    {% if (file.error) { %}
    <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
    {% } else if (o.files.valid && !i) { %}
    <td>
      <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
    </td>
    <td class="start">{% if (!o.options.autoUpload) { %}
      <button class="btn btn-primary">
        <i class="icon-upload icon-white"></i>
        <span>{%=locale.fileupload.start%}</span>
      </button>
      {% } %}</td>
    {% } else { %}
    <td colspan="2"></td>
    {% } %}
    <td class="cancel">{% if (!i) { %}
      <button class="btn btn-warning">
        <i class="icon-ban-circle icon-white"></i>
        <span>{%=locale.fileupload.cancel%}</span>
      </button>
      {% } %}</td>
  </tr>
  {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  <tr class="template-download fade">
    {% if (file.error) { %}
    <td></td>
    <td class="name"><span>{%=file.name%}</span></td>
    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
    <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
    {% } else { %}
    <td class="preview">{% if (file.thumbnail_url) { %}
      <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
      {% } %}</td>
    <td class="name">
      <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
    </td>
    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
    <td colspan="2"></td>
    {% } %}
    <td class="delete">
      <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
        <i class="icon-trash icon-white"></i>
        <span>{%=locale.fileupload.destroy%}</span>
      </button>
      <input type="checkbox" name="delete" value="1">
    </td>
  </tr>
  {% } %}
</script>

<script type="text/javascript" charset="utf-8">
    $(function () {
        // Initialize the jQuery File Upload widget:
        $('#fileupload').fileupload();
        //
        // Load existing files:
        $.getJSON($('#fileupload').prop('action'), function (files) {
            var fu = $('#fileupload').data('blueimpFileupload'),
                    template;
            fu._adjustMaxNumberOfFiles(-files.length);
            console.log(files);
            template = fu._renderDownload(files)
                    .appendTo($('#fileupload .files'));
            // Force reflow:
            fu._reflow = fu._transition && template.length &&
                    template[0].offsetWidth;
            template.addClass('in');
            $('#loading').remove();
        });

    });
</script>

app/views/books/index.html.haml
%h1 Listing books

%table
  %tr
    %th Id
    %th Bname
    %th Btype
    %th Bdescript
    %th Bprice
    %th Bpublication
    %th
    %th
    %th

  - @books.each do |book|
    %tr
      %td= book.id
      %td= book.bname
      %td= book.btype
      %td= book.bdescript
      %td= book.bprice
      %td= book.bpublication
      %td= link_to 'Show', book
      %td= link_to 'Edit', edit_book_path(book)
      %td= link_to 'Destroy', book, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Book', new_book_path
= link_to 'mail to author', sendmail_book_path(1)

app/views/books/new.html.haml
%h1 New book

= render 'form'

= link_to 'Back', books_path

app/views/books/search.js.erb
$('#searchlist').html("<%= escape_javascript(render :partial => 'books/search', :locals => {:opt => 'param'}) %>");

app/views/books/show.html.haml
%p#notice= notice

%p
  %b Id:
  = @book.id
%p
  %b Bname:
  = @book.bname
%p
  %b Btype:
  = @book.btype
%p
  %b Bdescript:
  = @book.bdescript
%p
  %b Bprice:
  = @book.bprice
%p
  %b Bpublication:
  = @book.bpublication

= link_to 'Edit', edit_book_path(@book)
\|
= link_to 'Back', books_path